//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EresData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public Grades()
        {
            this.GradeValues = new HashSet<GradeValues>();
        }
    
        public int GradeID { get; set; }
        public int RealisationID { get; set; }
        public string Name { get; set; }
        public string MaxValue { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual Realisations Realisations { get; set; }
        public virtual ICollection<GradeValues> GradeValues { get; set; }
    }
}
