//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EresData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTR2013Entities : DbContext
    {
        public NTR2013Entities()
            : base("name=NTR2013Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Grades> Grades { get; set; }
        public DbSet<GradeValues> GradeValues { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Realisations> Realisations { get; set; }
        public DbSet<Registrations> Registrations { get; set; }
        public DbSet<Semesters> Semesters { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<Subjects> Subjects { get; set; }
    }
}
