//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EresData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realisations
    {
        public Realisations()
        {
            this.Grades = new HashSet<Grades>();
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int RealisationID { get; set; }
        public int SubjectID { get; set; }
        public int SemesterID { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual Semesters Semesters { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual ICollection<Registrations> Registrations { get; set; }
    }
}
